// Code generated by "stringer -type Subject"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Broadcast-0]
	_ = x[Ready-1]
	_ = x[Action-2]
}

const _Subject_name = "BroadcastReadyAction"

var _Subject_index = [...]uint8{0, 9, 14, 20}

func (i Subject) String() string {
	if i < 0 || i >= Subject(len(_Subject_index)-1) {
		return "Subject(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Subject_name[_Subject_index[i]:_Subject_index[i+1]]
}
