FROM python:3.13-slim

RUN apt-get update && apt-get install -y libpq-dev build-essential

VOLUME ["/app"]
WORKDIR /app

COPY ./requirements.txt /tmp/
RUN pip install --requirement /tmp/requirements.txt

EXPOSE 8080
CMD ["uvicorn", "app.main:app", "--reload", "--port", "8080", "--host", "0.0.0.0"]