FROM nginx

#RUN apk add --no-cache openssl nginx gettext \
#    && mkdir -p /etc/nginx/ssl/ \
#    && openssl req -new -x509 -sha256 -newkey rsa:2048 -days 365 -nodes -out /etc/nginx/ssl/nginx.pem -keyout /etc/nginx/ssl/nginx.key -subj "/C=JP/ST=MyState/L=MyLocality/O=MyOrg/OU=dev/CN=local.dev" \
#    && mkdir -p /run/nginx/


COPY ./dev/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./dev/nginx/entrypoint.sh .

EXPOSE 443
EXPOSE 8080
STOPSIGNAL SIGTERM

ENTRYPOINT sh entrypoint.sh
